title: Pythia
description: Pythia documentation
theme: just-the-docs

url: https://vedph.github.io/pythia-doc

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

mermaid:
  version: "11.4.1"

enable_copy_code_button: true

nav_sort: case_insensitive
